// @constants/ouschedule.ts
import type { Game } from '../types/espn';

export const preloadedOUSchedule: Game[] = [
  {
    id: '20240829',
    date: 'Fri, Aug 29',
    time: 'TBD',
    homeTeam: 'Illinois St',
    awayTeam: 'Oklahoma',
    venue: 'Memorial Stadium (Norman, OK)',
    isHome: true,
  },
  {
    id: '20240905',
    date: 'Fri, Sep 5',
    time: 'TBD',
    homeTeam: 'Michigan',
    awayTeam: 'Oklahoma',
    venue: 'Memorial Stadium (Norman, OK)',
    isHome: true,
  },
  {
    id: '20240912',
    date: 'Fri, Sep 12',
    time: 'TBD',
    homeTeam: 'Oklahoma',
    awayTeam: 'Temple',
    venue: 'Lincoln Financial Field',
    isHome: false,
  },
  {
    id: '20240919',
    date: 'Fri, Sep 19',
    time: 'TBD',
    homeTeam: 'Auburn',
    awayTeam: 'Oklahoma',
    venue: 'Memorial Stadium (Norman, OK)',
    isHome: true,
  },
  {
    id: '20241003',
    date: 'Fri, Oct 3',
    time: 'TBD',
    homeTeam: 'Kent State',
    awayTeam: 'Oklahoma',
    venue: 'Memorial Stadium (Norman, OK)',
    isHome: true,
  },
  {
    id: '20241010',
    date: 'Fri, Oct 10',
    time: 'TBD',
    homeTeam: 'Oklahoma',
    awayTeam: 'Texas',
    venue: 'Cotton Bowl',
    isHome: false,
  },
  {
    id: '20241017',
    date: 'Fri, Oct 17',
    time: 'TBD',
    homeTeam: 'Oklahoma',
    awayTeam: 'South Carolina',
    venue: 'Williams-Brice Stadium',
    isHome: false,
  },
  {
    id: '20241024',
    date: 'Fri, Oct 24',
    time: 'TBD',
    homeTeam: 'Ole Miss',
    awayTeam: 'Oklahoma',
    venue: 'Memorial Stadium (Norman, OK)',
    isHome: true,
  },
  {
    id: '20241031',
    date: 'Fri, Oct 31',
    time: 'TBD',
    homeTeam: 'Oklahoma',
    awayTeam: 'Tennessee',
    venue: 'Neyland Stadium',
    isHome: false,
  },
  {
    id: '20241114',
    date: 'Fri, Nov 14',
    time: 'TBD',
    homeTeam: 'Oklahoma',
    awayTeam: 'Alabama',
    venue: 'Bryant-Denny Stadium',
    isHome: false,
  },
  {
    id: '20241121',
    date: 'Fri, Nov 21',
    time: 'TBD',
    homeTeam: 'Missouri',
    awayTeam: 'Oklahoma',
    venue: 'Memorial Stadium (Norman, OK)',
    isHome: true,
  },
  {
    id: '20241128',
    date: 'Fri, Nov 28',
    time: 'TBD',
    homeTeam: 'LSU',
    awayTeam: 'Oklahoma',
    venue: 'Memorial Stadium (Norman, OK)',
    isHome: true,
  },
];